### ISSUE TITLE
inconsistent historical ohlc 

### ISSUE THREAD

**Issue by squeaky-godzilla** [veox/python3-krakenex#112]
### Versions

```
OS:       Ubuntu 18.04
Python:   3.6.7
krakenex: 2.1.0
```

### What are you trying to achieve?
get the historical data and update current dataframe with it.

pull original dataframe via pykrakenapi
wait
pull updated dataframe
concatenate dataframes and drop duplicates

``` python
# code sample

```

### What do you expect to happen?
dataframe updated with new new lines, duplicate rows from the new dataframe will be dropped as they already exist in the old one

### What happens instead?
some of the rows remain, as they have the same datetime index, but different values in series (ie. the closing or opening price is different)

**Comment by veox** [comment]
Issues involving `pykrakenapi` should be reported on its bug tracker, not here.

-----

That said - yes, this is a known upstream (Kraken's) implementation detail. Using plain `krakenex` produces the same result.

Here's [a (historic) gist](https://gist.github.com/veox/10f857873941a15910054cbbbb9d4592) when this has first been brought to my attention. Rather annoyingly, the discussion is in a sub-reddit (`/r/ethtraders`) that has since been made private, so I can't reasonably link it (or copy-paste, for that matter, as I don't have access).

This can (theoretically) be explained by OHLC data being provided by a cluster of machines accessed through a high-availability/load-balancing proxy; and the machines having different data (for unknown reason)... But that's just guesswork.

Anyway, yes - this is an annoyance, and there seems nothing can be done... except contacting Kraken. ;)

**Comment by veox** [comment]
For ref, the script used to produce the gist was (quite likely an earlier version of)

https://github.com/veox/python3-krakenex/blob/master/examples/log-ohlc.py
