### ISSUE TITLE
websocket callback does not receive messages

### ISSUE THREAD

**Issue by kkagill** [veox/python3-krakenex#121]
### Versions

```
OS: windows10       
Python: 3.7.7
krakenex: 
```

### What are you trying to achieve?

Testing websocket with kraken public library (https://github.com/krakenfx/kraken-wsclient-py)
Seems that it's not receiving any messages.

``` python

from kraken_wsclient_py import kraken_wsclient_py as client

def my_handler(message):
    # Here you can do stuff with the messages
    print(message)

my_client = client.WssClient()
my_client.start()

# Sample public-data subscription:

my_client.subscribe_public(
    subscription = {
        'name': 'trade'
    },
    pair = ['XBT/USD', 'XRP/USD'],
    callback = my_handler
)

```

### What do you expect to happen?
`my_handler` receives messages via callback

### What happens instead?
Nothing happens for a few minutes. Then I get 
`{'e': 'error', 'm': 'Max reconnect retries reached'}` from `my_handler`

Is this library still relevant? Has anyone tried this?

**Comment by veox** [comment]
> Is this library still relevant?

This repo is for the REST API package, not the WS API.

Therefore marking issue as invalid.

-----

> Has anyone tried this?

However, considering your question is from their README sample, I'd guess it "should just work".

I don't use Windows, and don't know which toolset you're using (plain Python? Anaconda?..), but I'd hazard a guess you're not getting any output because it's buffered.

Try specifying the `-u` flag to `python`, as in:

`python -u ./my_script.py`

... or, if you're using an IDE of some sort, look for an option of the same name.
