### ISSUE TITLE
Depth function not returning asks or bids sometimes.

### ISSUE THREAD

**Issue by rjb25** [veox/python3-krakenex#20]
This [example code](https://github.com/veox/python3-krakenex/blob/640ac393b62015d3ef1ea499ae395c9ef49f3329/examples/Depth.py) you provided. Will occasionally return an object like this
```
{'error': [], 'result': {'XETHXXBT': {'bids': [], 'asks': [['0.090513', '0.747', 1496336370], ['0.090519', '15.146', 1496336378]]}}}
```
When asking for a depth of 4. In other words I am 6 orders short. I got no bids... Is there a more consistent order book function I am missing? Why might this be happening? 

-----

EDIT: link to commit where `Depth.py` is still present.

**Comment by veox** [comment]
> Why might this be happening?

No idea. :(

You indeed seem to be missing 4 orders on the `bids` side, and 2 on the `asks`.

Does this happen on any other pair other than ETH/XBT?

**Comment by smechaab** [comment]
I used to have this error too and I think this comes from the kraken's servers which are sometimes busy and can't properly send results

**Comment by veox** [comment]
I've received an e-mail pertaining to a different sort of historic data mangling, at about the same time period as when this issue was opened. At least it seems like data mangling to me - server-side or in-transit.

@rjb25:

* Do you still experience these events?
* Do you log them?
* Do you measure round-trip time for request/response, or are you using just that one-liner?
* Can it be correlated with, say, [downtime](https://status.kraken.com/) events?

**Comment by veox** [comment]
Closing as no-response.
