### ISSUE TITLE
Conditional Close with different pairs

### ISSUE THREAD

**Issue by AdityaNayak** [veox/python3-krakenex#39]
### Versions

```
OS: Mac OSX
Python:  3
krakenex: 1.0.0
```

### What are you trying to achieve?

Conditional close with 2 different pairs

``` python
k.query_private('AddOrder', {'pair': XXBTZUSD,
                             'type': 'buy',
                             'ordertype': 'limit',
                             'price': usdask,
                             'volume': volume[j],
                             'close[pair]': XXBTZEUR,
                             'close[type]': 'sell',
                             'close[ordertype]': 'limit',
                             'close[price]': eurask,
                             'close[volume]': volume[j] })
```

### What do you expect to happen?

Order that buys btc in usd and sells in Euro

### What happens instead?

Buys and sells both in USD

``` python
# error message
No error message
```

**Comment by veox** [comment]
Either I didn't sufficiently test the example when putting it in the repo, or the API changed on Kraken's side without a version bump.

I've also noticed (a few months ago) that some `close[...]` attributes have no effect - `close[volume]`, I think?..

**Comment by AdityaNayak** [comment]
Do you have a workaround in mind?

**Comment by veox** [comment]
I don't think there can be a workaround, other than running a monitoring bot.

Below somewhat OT.

-----

[Kraken's API docs](https://www.kraken.com/help/api#add-standard-order) currently lists these as possible:

> optional closing order to add to system when order gets filled:
> close[ordertype] = order type
> close[price] = price
> close[price2] = secondary price

The Wayback Machine [suggests](https://web.archive.org/web/20130928094848/https://www.kraken.com/help/api#add-standard-order) that it never really did list anything else.

It _could_ be that Kraken decided to limit what fields are acceptable here, and ignore the rest.

Again, I'm not _sure_ if it ever accepted anything else. The fact that `examples/conditional-close.py` has shown more fields, ever since it was added in commit https://github.com/veox/python3-krakenex/commit/15dd9ee983cd557edd5fa67bd7effcc32c7cfe2d tends to suggest that it did, or that I'm delusional.

I do remember testing that example with a live market order, though...

**Comment by AdityaNayak** [comment]
So, Kraken replied. 

> Hello there,
> 
> I did some more digging and it turns out we do not allow separate pairs beyond the base pairs for conditional close orders. Sorry I don't have better news.
