### ISSUE TITLE
Help Getting History Data 

### ISSUE THREAD

**Issue by Metaphor31** [veox/python3-krakenex#51]
### Versions

```
OS:       
Python: 3.6
krakenex: 0.1.4
```

### What are you trying to achieve?
I want to create a function returning a dataframe with all prices history for a list of pairs, 
For example all closing prices between 2015 and 2017 for BTCUSD and ETHEUR. 

1st Step is to know how to download history with dates. as parameters.

``` python
# code sample
k = krakenex.API()
k.load_key('kraken.key.txt')
ticker_1 = k.query_public('Ticker', {'pair': 'XXBTZUSD'}) #here I want to add parameters to ask for a #specific dates or period. 
ticker_1 = k.query_public('Ticker', {'pair': 'XXBTZUSD'},req(start_date, end_date, 1) )
```

### What do you expect to happen?

``` python
#I have found this : 
th = k.query_private('TradesHistory', req(start_date, end_date, 1))
#I would like to transpose it not with tradeshistory but just ticker and dates but doing this : 
ticker_1 = k.query_public('Ticker', {'pair': 'XXBTZUSD'},req(start_date, end_date, 1) )
# does not work
```

### What happens instead?

``` python
ticker_1 = k.query_public('Ticker', {'pair': 'XXBTZUSD'},req(start_date, end_date, 1) )
error: AttributeError: 'dict' object has no attribute '_request'

# Output of the line : 
ticker_1 = k.query_public('Ticker', {'pair': 'XXBTZUSD'})
# Am I supposed to get this : 'error': [],
# Output : 
{'error': [],
 'result': {'XXBTZUSD': {'a': ['4307.30000', '1', '1.000'],
   'b': ['4305.60000', '3', '3.000'],
   'c': ['4305.50000', '0.03977220'],
   'h': ['4399.00000', '4399.00000'],
   'l': ['4211.10000', '4180.10000'],
   'o': '4226.20000',
   'p': ['4306.30564', '4281.68920'],
   't': [8134, 13490],
   'v': ['2470.05812705', '3969.08612297']}}}

**Comment by veox** [comment]
Note: I've edited the report formatting somewhat.

**Comment by veox** [comment]
Kraken's [docs for `Ticker`](https://www.kraken.com/help/api#get-ticker-info) suggest that the only thing you can specify for it is `pair`.

For your use case, what you want is [`OHLC`](https://www.kraken.com/help/api#get-ohlc-data). Take a look at [`examples/log-ohlc.py`](https://github.com/veox/python3-krakenex/blob/b66a413958a90057deb5d0aa2e0cb9ba2c24d95f/examples/log-ohlc.py).

Note that `since` might be tricky, as discussed in #44.

The example doesn't change the default `interval`, which is touched on in the comments. For a weekly, you'd want `10080` (60*24*7).

-----

Finally,

``` python
ticker_1 = k.query_public('Ticker', {'pair': 'XXBTZUSD'},req(start_date, end_date, 1) )
```

... doesn't work, because the third positional parameter is a `krakenex.Connection` - see [docs](https://python3-krakenex.readthedocs.io/en/v0.1.4/#krakenex.API.query_public).

**Comment by veox** [comment]
Somewhat OT: Take a look at the [Reddit thread](https://www.reddit.com/r/kraken_traders/comments/6f6e9h/krakenapi_delivering_inconsistent_false_ohlc_data/) that spawned the example (also linked from therein).

Depending on your final final use of the retrieved dataframe, you _might_ be disapponted, since the data _could_ change ever so slightly.

At the time of that Reddit discussion, the previous statement used to be true. I've decided not to implement a monitoring bot that would keep checking if the fact has changed, seeing how Kraken's API is already overloaded.

If your application does not require _strict_ historic data consistency, and you decide to go ahead with it, be sure to save responses. `krakenex` does not provide such facilities.

**Comment by veox** [comment]
OK to close?..

**Comment by Metaphor31** [comment]
Thanks Noel,
I have found other ways to solve my problem,
Best
Alex

2017-09-21 13:56 GMT+01:00 Noel Maersk <notifications@github.com>:
