### ISSUE TITLE
502 Server Error: Bad Gateway for url: https://api.kraken.com/0/private/AddOrder

### ISSUE THREAD

**Issue by yepla** [veox/python3-krakenex#60]
Hello,
Actually kraken seems ddos and sometime when i made and order by using AddOrder i have got this:
502 Server Error: Bad Gateway for url: https://api.kraken.com/0/private/AddOrder
The order is set but i don't get the txids :(
Does it's a bug on krakenex or on kraken ?
Don't know but i really need this txids so how can i do ?
Thanks.

**Comment by veox** [comment]
It's an issue somewhere between Kraken/Cloudflare.

I've described it in a recent [PSA on Reddit](https://www.reddit.com/r/krakenex/comments/778uvh/psa_http_error_502_does_not_mean_the_query_wont/).

The underlying cause is network-related.

A workaround is to specify `userref` with a unique identifier when placing the order. With that in place, if you detect a 502 exception, you can at least fall back to:

* getting a full list of open orders;
* selecting the particular order by `userref`;
* getting the actual id.

As detailed in the PSA, a 502 means the order _may_ or _may not_ have reached Kraken's trade/orderbook engine. The delay is also non-deterministic, but seems to be below a minute ATM.

**Comment by veox** [comment]
[Kraken's docs](https://www.kraken.com/help/api#add-standard-order) specifies:

> userref = user reference id.  32-bit signed number.  (optional)

**Comment by yepla** [comment]
Does the userref must be each time be different ?
Could you give an exemple how to create the 32-bit signed number ?
If i get OpenOrders does the txids of the order is in refid ?

**Comment by veox** [comment]
One can get both open and closed orders; also, one can limit them to those matching a specific `userref`.

Consult Kraken's docs for more info.

**Comment by yepla** [comment]
One can get both open and closed orders
Which one please ?

**Comment by veox** [comment]
https://www.kraken.com/help/api#get-open-orders
https://www.kraken.com/help/api#get-closed-orders

**Comment by yepla** [comment]
Ok so in fact when i put a buy or sell order i check if it s open to get the txids this for one minute !
If i m not get it in the minute i check if it has been closed to get the txid if i m still not having the txid i say the order has not been set.
I don't know if it s the best but it seems work ...
