### ISSUE TITLE
Connection error  comes json.decoder.JSONDecodeError: Expecting value:  

### ISSUE THREAD

**Issue by rasdehya** [veox/python3-krakenex#70]
### Versions

OS: Windows10
Python: 3.6
krakenex: ~~3.0~~ 2

### What are you trying to achieve?
i try to make pubic query over kraken API, but i get a recursive error but it doest come each time. 
```
for asset in my_pair:
            response = k.query_public('Depth', {'pair': asset, 'count': '3'})
```
### What do you expect to happen?
Normally i get the result that i can format

### What happens instead?
```
  File "C:\Users\ras\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

It 'seems like a connection problem... I've seen a past issue that had been closed
i get an empty dict from the API ?? is it ?

I'm really new to prog and python, and i struggle with error handling...

I'm suprise i didnt get a time out or something like that, or  a 502
Must i deal with try/catch ? someone has a trick for that ?
How could i know wich error to look at ? so i can repeat the query till successful

Sorry if too obvious.... tell me and i will google more

Thanks

**Comment by veox** [comment]
The latest version of `krakenex` is `v2.0.0`.

The error looks like what you'd get in `v0` and `v1`.

How did you install it?..

-----

Otherwise - correct, it's a connection problem, which you're likely to experience a lot these days with Kraken.

**Comment by rasdehya** [comment]
Thanks for reply Veox.
I installed it via pip  with python 3.6 in windows 10
And yes V2.0 .... :-)) it was 3.0 of GPL.... hahaha... really new into all that.
`EDIT: In v2, exceptions raised due to networking errors should all be requests.exceptions.HTTPError.`

Exactly that is what i expected.
But What you say is that i have to try/catch this one in order to succeed ? or should it be raised automaticly by krakenex?...

at the time i write, my script work just fine...no connection pb with kraken

**Comment by veox** [comment]
It's very strange that you get _that_ error, if it's _really_ at `v2`... Could you try this in your script?

``` python
print(krakenex.version.__version__)
```

It _might_ be that you have several versions installed, and the script is picking up a different one than you think.

If it does say `'2.0.0'` - could you try force-reinstalling?..

I've never used `pip` on Windows, so can't help much here. On Linux, it'd be something like `pip install --upgrade krakenex`.

Otherwise, what's in `my_pair`?..

-----

> But What you say is that i have to try/catch this one in order to succeed ? or should it be raised automaticly by krakenex?...

The exception is raised automatically by `krakenex` on network errors.

Here's a [gist](https://gist.github.com/veox/fa2a406de0a0dcfda234374fa014e444) with a real-world example of how I'm using `try/except` in a script to debug an issue (#66)... Perhaps it's too convoluted if you're new to programming, though. :(

**Comment by veox** [comment]
Closing as stale.
